services:
  # backup:
  #   entrypoint: /cron.sh
  #   env_file: .env
  #   image: nextcloud:production-fpm-alpine
  #   restart: always
  #   depends_on:
  #     - cache
  #     - database
  #   volumes_from:
  #     - cloud
  cache:
    command: redis-server --requirepass $REDIS_HOST_PASSWORD
    env_file: .env
    image: redis:alpine
    restart: always
    volumes:
      - ./cache/content:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  cloud:
    env_file: .env
    image: nextcloud:31.0.7-fpm-alpine
    restart: always
    depends_on:
      - cache
      - database
    volumes: # Other volumes do not persist during updates!
      - /zfs/cloud/config:/var/www/html/config
      - /zfs/cloud/custom_apps:/var/www/html/custom_apps
      - /zfs/cloud/data:/var/www/html/data
      - /zfs/cloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  database:
    env_file: .env
    image: mariadb:10.11 # Select NC compatible version
    restart: always
    volumes:
      - /zfs/database/config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - /zfs/database/content:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  office:
    env_file: .env
    image: onlyoffice/documentserver:latest
    restart: always
    expose:
      - "80"
    volumes:
      # - /zfs/office/cache:/var/lib/onlyoffice
      # - /zfs/office/certs:/var/www/onlyoffice/Data/certs
      - /zfs/office/config:/etc/onlyoffice/documentserver
      # - /zfs/office/data:/var/www/onlyoffice/postgresql
      - /zfs/office/logs:/var/log/onlyoffice
  webserver:
    env_file: .env
    image: caddy:alpine
    restart: always
    depends_on:
      - cloud
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /zfs/webserver/data:/data
      - /zfs/webserver/config:/config
      - /zfs/webserver/caddy:/etc/caddy/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    volumes_from:
      - cloud
